spring:
  application:
    name: webapplication
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      provided_paths: "/,/hallo"
management:
  endpoint:
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: mappings